schema_version = "1.0.0"
id = "parsnevis"
version = "1.0.0"
name = "parsnevis"
tagline = "Correcting the formatting of Persian and Arabic texts in Blender"
maintainer = "Amirsolic"
type = "add-on"
tags = ["3D View"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-2.0-or-later",
]